---
- hosts: all 
  become: yes
  tasks:
  - name: install apache on redhat
    yum:
     name: httpd
     state: present 
    when: ansible_distribution == "RedHat"
    service:
     name: httpd
     state: started
  - name: install apache on Ubuntu 
    get:
     name: apache2 
     state: present
    when: ansible_distribution == "Ubuntu"
    service:
     name: apache2 
     state: started

